### ISSUE TITLE
Case-sensitive file systems cause crash for raw/graphics/Beefmo

### ISSUE THREAD

**Issue by ad2476** [DFgraphics/Afro-Graphics#1]
This didn't seem worth creating a pull request over, as it seems an easy fix: raw/graphics/graphics_beefmoanimals.txt should use FILE:Beefmo/Animals/[...] for each of the files. OR rename Beefmo/Animals to beefmo/animals and change raw/graphics/graphics_beefmohumans.txt to use FILE:beefmo/humans.png

**Comment by fricy** [comment]
thx, fixed
